sudo: required
services:
  - docker

before_install:
  - docker build -t antogc/docker-react -f Dockerfile.dev .

script:  #script should return 0 to success
  - docker run antogc/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-eu-west-1-926824671793"
  path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
